INSERT INTO MOVIES () VALUES ("Il padrino",1990,"Frank","Holland",10,"Comedy",50000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("I predatori dell'arca perduta",2000,"Checco","US",6,"Mystery",50000000,"Universal");
INSERT INTO MOVIES () VALUES ("L'Impero colpisce ancora",1988,"Gigi","Spain",8,"Horror",60000000,"Pixar");
INSERT INTO MOVIES () VALUES ("Le ali della liberta",1970,"Gio","US",3,"Horror",40000000,"Universal");
INSERT INTO MOVIES () VALUES ("Lo squalo",1960,"Chiara","China",2,"Thriller",8000000,"Time");
INSERT INTO MOVIES () VALUES ("Quei bravi ragazzi",1950,"Gigi","Germany",5,"Mystery",100000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Apocalypse Now",1999,"Alberto","US",2,"Action",40000000,"HBO");
INSERT INTO MOVIES () VALUES ("Cantando sotto la pioggia",2020,"Chiara","Qatar",8,"Horror",50000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Pulp Fiction",1960,"Paolo","Greece",7,"Gore",100000000,"Pixar");
INSERT INTO MOVIES () VALUES ("Fight Club",2010,"Frank","Holland",3,"Comedy",70000000,"Disney");
INSERT INTO MOVIES () VALUES ("Toro scatenato",1990,"Gio","Italy",1,"Erotic",10000000,"Time");
INSERT INTO MOVIES () VALUES ("L'appartamento",1989,"Michele","Holland",4,"Erotic",90000000,"HBO");
INSERT INTO MOVIES () VALUES ("Chinatown",1989,"Michele","China",2,"Thriller",70000000,"Fox");
INSERT INTO MOVIES () VALUES ("C'era una volta il West",1970,"Marco","China",9,"History",40000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Il cavaliere oscuro",1970,"Michele","China",10,"Mystery",40000000,"Pixar");
INSERT INTO MOVIES () VALUES ("2001: Odissea nello spazio",1997,"Nicolo","US",7,"Adventure",70000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Taxi Driver",1920,"Checco","Germany",8,"Erotic",10000000,"Universal");
INSERT INTO MOVIES () VALUES ("Casablanca",2010,"Checco","Greece",7,"Drama",10000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Il padrino - Parte II",1997,"Gigi","Italy",1,"Horror",20000000,"CNN");
INSERT INTO MOVIES () VALUES ("Blade Runner",2001,"Checco","Qatar",2,"History",10000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Il terzo uomo",1950,"Chiara","Japan",6,"Adventure",40000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Guerre stellari",1960,"Paolo","Spain",7,"Horror",90000000,"Pixar");
INSERT INTO MOVIES () VALUES ("Ritorno al futuro",2000,"Paolo","Greece",3,"Drama",10000000,"Disney");
INSERT INTO MOVIES () VALUES ("Il Signore degli Anelli - La Compagnia dell'Anello",1920,"Gigi","Greece",4,"Gore",8000000,"CNN");
INSERT INTO MOVIES () VALUES ("Il buono, il brutto, il cattivo",1999,"Gio","Italy",5,"Thriller",20000000,"Fox");
INSERT INTO MOVIES () VALUES ("Il dottor Stranamore",1989,"Michele","US",5,"Gore",100000000,"Disney");
INSERT INTO MOVIES () VALUES ("A qualcuno piace caldo",1960,"Checco","China",1,"Gore",90000000,"Apple");
INSERT INTO MOVIES () VALUES ("Quarto potere",1999,"Gigi","Qatar",4,"Gore",40000000,"Disney");
INSERT INTO MOVIES () VALUES ("Trappola di cristallo",1997,"Nicolo","Spain",10,"Action",40000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Aliens - Scontro finale",1989,"Alberto","China",7,"Erotic",100000000,"Fox");
INSERT INTO MOVIES () VALUES ("Via col vento",1920,"Nicolo","France",10,"Erotic",50000000,"Disney");
INSERT INTO MOVIES () VALUES ("Butch Cassidy",1980,"Alberto","Holland",8,"Adventure",40000000,"HBO");
INSERT INTO MOVIES () VALUES ("Alien",1960,"Frank","Spain",1,"Gore",90000000,"Fox");
INSERT INTO MOVIES () VALUES ("Il Signore degli Anelli - Il ritorno del re",1990,"Marco","France",8,"Erotic",90000000,"Apple");
INSERT INTO MOVIES () VALUES ("Terminator 2 - Il giorno del giudizio",2020,"Frank","Qatar",1,"Erotic",90000000,"Universal");
INSERT INTO MOVIES () VALUES ("Andrej Rublev",1990,"Michele","France",2,"Thriller",90000000,"Time");
INSERT INTO MOVIES () VALUES ("Arancia meccanica",1999,"Nicolo","Spain",3,"Thriller",90000000,"Time");
INSERT INTO MOVIES () VALUES ("Heat - La sfida",1960,"Frank","US",7,"Action",30000000,"Apple");
INSERT INTO MOVIES () VALUES ("Matrix",1999,"Marco","Spain",8,"Erotic",20000000,"Pixar");
INSERT INTO MOVIES () VALUES ("La donna che visse due volte",1920,"Chiara","Germany",1,"Comedy",30000000,"Time");
INSERT INTO MOVIES () VALUES ("I 400 colpi",1990,"Marco","Germany",6,"Erotic",20000000,"Disney");
INSERT INTO MOVIES () VALUES ("Sangue blu",1980,"Checco","Qatar",7,"Gore",60000000,"Universal");
INSERT INTO MOVIES () VALUES ("Il grande Lebowski",1950,"Gio","Japan",2,"Action",100000000,"Universal");
INSERT INTO MOVIES () VALUES ("Schindler's List",1970,"Chiara","Holland",6,"Mystery",30000000,"Disney");
INSERT INTO MOVIES () VALUES ("Psyco",1988,"Chiara","Germany",9,"Comedy",60000000,"Universal");
INSERT INTO MOVIES () VALUES ("Fronte del porto",2000,"Checco","Japan",10,"History",70000000,"Apple");
INSERT INTO MOVIES () VALUES ("E.T. l'extra-terrestre",1989,"Gio","Spain",8,"Mystery",40000000,"Apple");
INSERT INTO MOVIES () VALUES ("This Is Spinal Tap",1980,"Gigi","Holland",5,"Mystery",30000000,"Disney");
INSERT INTO MOVIES () VALUES ("La casa 2",1990,"Nicolo","Greece",4,"Adventure",70000000,"Pixar");
INSERT INTO MOVIES () VALUES ("I sette samurai",2020,"Gio","Germany",6,"Horror",90000000,"Universal");
INSERT INTO MOVIES () VALUES ("8",1988,"Gio","Holland",2,"Horror",70000000,"Disney");
INSERT INTO MOVIES () VALUES ("Shining",1999,"Gio","Germany",1,"Mystery",20000000,"Apple");
INSERT INTO MOVIES () VALUES ("Donnie Darko",1920,"Michele","Holland",4,"Erotic",30000000,"Apple");
INSERT INTO MOVIES () VALUES ("Il Signore degli Anelli - Le due torri",1980,"Marco","Holland",4,"Thriller",100000000,"Time");
INSERT INTO MOVIES () VALUES ("La dolce vita",1960,"Marco","US",9,"Mystery",8000000,"Disney");
INSERT INTO MOVIES () VALUES ("Casino Royale",1980,"Michele","Holland",5,"Action",50000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Lawrence d'Arabia",2010,"Frank","Qatar",8,"Comedy",40000000,"Apple");
INSERT INTO MOVIES () VALUES ("La signora del venerdi",1999,"Nicolo","France",9,"Adventure",10000000,"HBO");
INSERT INTO MOVIES () VALUES ("Incontri ravvicinati del terzo tipo",2010,"Checco","Japan",3,"History",40000000,"Fox");
INSERT INTO MOVIES () VALUES ("Va' e vedi",1997,"Gigi","US",3,"Adventure",50000000,"HBO");
INSERT INTO MOVIES () VALUES ("I soliti sospetti",2020,"Marco","US",6,"Adventure",60000000,"Universal");
INSERT INTO MOVIES () VALUES ("Il laureato",1950,"Paolo","Qatar",1,"Action",70000000,"Universal");
INSERT INTO MOVIES () VALUES ("Viale del tramonto",2000,"Gigi","Germany",6,"Comedy",10000000,"CNN");
INSERT INTO MOVIES () VALUES ("Old Boy",1980,"Michele","Italy",1,"Mystery",8000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Harold e Maude",1980,"Frank","Holland",7,"Mystery",100000000,"CNN");
INSERT INTO MOVIES () VALUES ("Edward mani di forbice",1950,"Michele","US",4,"Gore",70000000,"Pixar");
INSERT INTO MOVIES () VALUES ("Viaggio a Tokyo",2020,"Paolo","Qatar",1,"Horror",100000000,"CNN");
INSERT INTO MOVIES () VALUES ("Io e Annie",1989,"Checco","Spain",6,"Comedy",8000000,"Fox");
INSERT INTO MOVIES () VALUES ("Tre colori - Film rosso",2020,"Nicolo","Spain",3,"Erotic",50000000,"Disney");
INSERT INTO MOVIES () VALUES ("Stand by Me - Ricordo di un'estate",1950,"Frank","Japan",8,"Mystery",50000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("La morte corre sul fiume",2020,"Checco","Spain",4,"Horror",30000000,"Fox");
INSERT INTO MOVIES () VALUES ("La parola ai giurati",1988,"Gio","France",1,"Action",60000000,"Time");
INSERT INTO MOVIES () VALUES ("Se mi lasci ti cancello",1980,"Alberto","Qatar",2,"Drama",20000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Il tesoro della Sierra Madre",1980,"Gigi","Italy",4,"Gore",50000000,"Fox");
INSERT INTO MOVIES () VALUES ("Scala al paradiso",1999,"Nicolo","China",9,"Adventure",10000000,"Apple");
INSERT INTO MOVIES () VALUES ("Manhattan",1999,"Paolo","Germany",10,"Gore",10000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Spartacus",1950,"Gigi","Qatar",4,"Gore",8000000,"CNN");
INSERT INTO MOVIES () VALUES ("Rosemary's Baby - Nastro rosso a New York",1980,"Paolo","Greece",5,"Adventure",90000000,"Fox");
INSERT INTO MOVIES () VALUES ("La sottile linea rossa",1988,"Alberto","Italy",3,"Thriller",60000000,"CNN");
INSERT INTO MOVIES () VALUES ("Duello a Berlino",1980,"Checco","Spain",8,"Thriller",70000000,"Paramount");
INSERT INTO MOVIES () VALUES ("Batman Begins",2010,"Checco","France",7,"Drama",100000000,"Pixar");
INSERT INTO MOVIES () VALUES ("La grande fuga",1999,"Chiara","Germany",2,"Mystery",70000000,"Alibaba");
INSERT INTO MOVIES () VALUES ("Brazil",2001,"Alberto","Greece",7,"Horror",100000000,"Time");
INSERT INTO MOVIES () VALUES ("L.A. Confidential",2010,"Chiara","Qatar",3,"Action",50000000,"CNN");
INSERT INTO MOVIES () VALUES ("Velluto blu",1999,"Checco","Greece",2,"Adventure",8000000,"HBO");
INSERT INTO MOVIES () VALUES ("Carrie - Lo sguardo di Satana",2000,"Gigi","Holland",3,"Adventure",90000000,"Time");
INSERT INTO MOVIES () VALUES ("Re per una notte",1988,"Gio","Italy",2,"Mystery",100000000,"Time");
INSERT INTO MOVIES () VALUES ("Una pazza giornata di vacanza",1920,"Gigi","Japan",9,"Comedy",40000000,"Time");
INSERT INTO MOVIES () VALUES ("Magnolia",2020,"Gio","Germany",7,"Action",8000000,"CNN");
INSERT INTO MOVIES () VALUES ("Harry ti presento Sally",1980,"Gigi","Germany",1,"Drama",90000000,"Universal");
INSERT INTO MOVIES () VALUES ("Il ritorno dello Jedi",1980,"Michele","Qatar",2,"Horror",30000000,"Time");
INSERT INTO MOVIES () VALUES ("C'era una volta in America",1960,"Alberto","Italy",4,"Thriller",40000000,"Universal");
INSERT INTO MOVIES () VALUES ("Lo spirito dell'alveare",1980,"Marco","France",8,"Comedy",90000000,"Universal");
INSERT INTO MOVIES () VALUES ("Il mucchio selvaggio",1980,"Paolo","Greece",9,"Comedy",20000000,"Apple");
INSERT INTO MOVIES () VALUES ("La sfida del samurai",2010,"Gigi","Holland",4,"Mystery",10000000,"Apple");
INSERT INTO MOVIES () VALUES ("American Beauty",1980,"Nicolo","France",10,"Mystery",90000000,"CNN");
INSERT INTO MOVIES () VALUES ("Le iene",2001,"Marco","China",6,"Erotic",40000000,"Pixar");
INSERT INTO MOVIES () VALUES ("Intrigo internazionale",2010,"Gigi","Qatar",8,"Drama",70000000,"Apple");
INSERT INTO MOVIES () VALUES ("Toy Story - Il mondo dei giocattoli",1920,"Nicolo","Qatar",2,"Action",40000000,"Fox");
INSERT INTO MOVIES () VALUES ("Quinto potere",2020,"Chiara","France",2,"Action",30000000,"HBO");


INSERT INTO ACTORS () VALUES ("La morte corre sul fiume",2020,"Edward Cullen","Henry Thomas");
INSERT INTO ACTORS () VALUES ("Velluto blu",1999,"Trinity","Madhur Mittal");
INSERT INTO ACTORS () VALUES ("Toy Story - Il mondo dei giocattoli",1920,"Truman Burbank","Clark Gable");
INSERT INTO ACTORS () VALUES ("This Is Spinal Tap",1980,"Andy Dufresne","Uma Thurman");
INSERT INTO ACTORS () VALUES ("Guerre stellari",1960,"Billy","Laurence Fishburne");
INSERT INTO ACTORS () VALUES ("Old Boy",1980,"Rick Deckard","Peter Fonda");
INSERT INTO ACTORS () VALUES ("Harry ti presento Sally",1980,"Mr. Miyagi","Daniel Radcliffe");
INSERT INTO ACTORS () VALUES ("Il grande Lebowski",1950,"Clarice Starling","Morgan Freeman");
INSERT INTO ACTORS () VALUES ("C'era una volta in America",1960,"detective David Mills","Uma Thurman");
INSERT INTO ACTORS () VALUES ("Alien",1960,"Bella Swan","Bruce Willis");
INSERT INTO ACTORS () VALUES ("Manhattan",1999,"Andy Dufresne","Anthony Hopkins");
INSERT INTO ACTORS () VALUES ("Ritorno al futuro",2000,"Jena Plissken","Pierfrancesco Favino");
INSERT INTO ACTORS () VALUES ("Velluto blu",1999,"Rick Deckard","Michael Clarke Duncan");
INSERT INTO ACTORS () VALUES ("Harold e Maude",1980,"Salim","Jodie Foster");
INSERT INTO ACTORS () VALUES ("Fronte del porto",2000,"Jamal Malik","Emile Hirsch");
INSERT INTO ACTORS () VALUES ("La sottile linea rossa",1988,"Molly Jensen","Gerard Butler");
INSERT INTO ACTORS () VALUES ("Blade Runner",2001,"Walt Kowalski","Al Pacino");
INSERT INTO ACTORS () VALUES ("Psyco",1988,"Harry Potter","Keanu Reeves");
INSERT INTO ACTORS () VALUES ("Fronte del porto",2000,"detective David Mills","Jamie Bell");
INSERT INTO ACTORS () VALUES ("La morte corre sul fiume",2020,"Dr. Henry Frankenstein","Jim Carrey");
INSERT INTO ACTORS () VALUES ("Alien",1960,"Johnny Castle","Tom Hanks");
INSERT INTO ACTORS () VALUES ("Una pazza giornata di vacanza",1920,"Morpheus","Clark Gable");
INSERT INTO ACTORS () VALUES ("I predatori dell'arca perduta",2000,"Dr. Henry Frankenstein","Tim Robbins");
INSERT INTO ACTORS () VALUES ("Quarto potere",1999,"Re Leonida","Christopher Lloyd");
INSERT INTO ACTORS () VALUES ("2001: Odissea nello spazio",1997,"Elliott","Keanu Reeves");
INSERT INTO ACTORS () VALUES ("Schindler's List",1970,"Vincent Vega","Kurt Russell");
INSERT INTO ACTORS () VALUES ("Schindler's List",1970,"Bruce Wayne","Anthony Edwards");
INSERT INTO ACTORS () VALUES ("Old Boy",1980,"Ten. Col. William  Bill  Kilgore","Robin Williams");
INSERT INTO ACTORS () VALUES ("Magnolia",2020,"Billy Elliot","Val Kilmer");
INSERT INTO ACTORS () VALUES ("I soliti sospetti",2020,"Marty McFly","Keir Dullea");
INSERT INTO ACTORS () VALUES ("La dolce vita",1960,"Jamal Malik","John Travolta");
INSERT INTO ACTORS () VALUES ("Il ritorno dello Jedi",1980,"Jack Dawson","Robin Williams");
INSERT INTO ACTORS () VALUES ("Via col vento",1920,"John Coffey","Marlon Brando");
INSERT INTO ACTORS () VALUES ("Io e Annie",1989,"Tenente Dan","Ian McKellen");
INSERT INTO ACTORS () VALUES ("Andrej Rublev",1990,"Tony Montana","Paul Newman");
INSERT INTO ACTORS () VALUES ("Matrix",1999,"Elwood Blues","Kevin Spacey");
INSERT INTO ACTORS () VALUES ("Il buono, il brutto, il cattivo",1999,"Dr. Henry Frankenstein","Michael Clarke Duncan");
INSERT INTO ACTORS () VALUES ("Va' e vedi",1997,"Norman Bates","Roy Scheider");
INSERT INTO ACTORS () VALUES ("Psyco",1988,"detective David Mills","Sigourney Weaver");
INSERT INTO ACTORS () VALUES ("A qualcuno piace caldo",1960,"Ed Bloom","Dwight Schultz");
INSERT INTO ACTORS () VALUES ("Casino Royale",1980,"John Keating","Jim Carrey");
INSERT INTO ACTORS () VALUES ("Le iene",2001,"Colin Sullivan","Dirk Benedict");
INSERT INTO ACTORS () VALUES ("Harold e Maude",1980,"Salim","Val Kilmer");
INSERT INTO ACTORS () VALUES ("C'era una volta il West",1970,"Guido Orefice","Val Kilmer");
INSERT INTO ACTORS () VALUES ("La casa 2",1990,"Eddie Felson","Tom Hanks");
INSERT INTO ACTORS () VALUES ("Apocalypse Now",1999,"Elwood Blues","Kate Winslet");
INSERT INTO ACTORS () VALUES ("Lo squalo",1960,"Eddie Felson","Kristen Stewart");
INSERT INTO ACTORS () VALUES ("Chinatown",1989,"Don Camillo","Madhur Mittal");
INSERT INTO ACTORS () VALUES ("Edward mani di forbice",1950,"Gandalf","Ian McKellen");
INSERT INTO ACTORS () VALUES ("Sangue blu",1980,"Er Pomata","Marlon Brando");
INSERT INTO ACTORS () VALUES ("Lawrence d'Arabia",2010,"Gandalf","Patrick Swayze");
INSERT INTO ACTORS () VALUES ("Matrix",1999,"Lt. Ellen Ripley","Brad Pitt");
INSERT INTO ACTORS () VALUES ("2001: Odissea nello spazio",1997,"Ethan Hunt","Madonna");
INSERT INTO ACTORS () VALUES ("Sangue blu",1980,"Capitano H. M. Murdock","Ewan McGregor");
INSERT INTO ACTORS () VALUES ("Heat - La sfida",1960,"Attila","Carrie-Anne Moss");
INSERT INTO ACTORS () VALUES ("8",1988,"Frank Costello","Demi Moore");
INSERT INTO ACTORS () VALUES ("Il mucchio selvaggio",1980,"Colonnello John  Hannibal  Smith","Kevin Spacey");
INSERT INTO ACTORS () VALUES ("Donnie Darko",1920,"Molly Jensen","Jamie Bell");
INSERT INTO ACTORS () VALUES ("Il Signore degli Anelli - Il ritorno del re",1990,"Andy Dufresne","Kevin Spacey");
INSERT INTO ACTORS () VALUES ("Terminator 2 - Il giorno del giudizio",2020,"Mark Renton","Tim Robbins");
INSERT INTO ACTORS () VALUES ("La casa 2",1990,"Colonnello Nathan Jessep","Harrison Ford");
INSERT INTO ACTORS () VALUES ("C'era una volta il West",1970,"Elliott","Michael Keaton");
INSERT INTO ACTORS () VALUES ("Il padrino",1990,"detective David Mills","Whoopi Goldberg");
INSERT INTO ACTORS () VALUES ("Incontri ravvicinati del terzo tipo",2010,"Lt. Ellen Ripley","Bruce Willis");
INSERT INTO ACTORS () VALUES ("Il laureato",1950,"Andy Dufresne","Pat Morita");
INSERT INTO ACTORS () VALUES ("Spartacus",1950,"Bruce Wayne","Leonardo DiCaprio");
INSERT INTO ACTORS () VALUES ("L'Impero colpisce ancora",1988,"Walt Kowalski","Al Pacino");
INSERT INTO ACTORS () VALUES ("La casa 2",1990,"Keyser Soze","Brad Pitt");
INSERT INTO ACTORS () VALUES ("Scala al paradiso",1999,"Alexander DeLarge","Marlon Brando");
INSERT INTO ACTORS () VALUES ("Il Signore degli Anelli - La Compagnia dell'Anello",1920,"Re Leonida","Madonna");
INSERT INTO ACTORS () VALUES ("La sottile linea rossa",1988,"Billy Elliot","Tom Cruise");
INSERT INTO ACTORS () VALUES ("Blade Runner",2001,"Andy Dufresne","Harrison Ford");
INSERT INTO ACTORS () VALUES ("Fronte del porto",2000,"Beatrix Kiddo","Robert Duvall");
INSERT INTO ACTORS () VALUES ("Lo spirito dell'alveare",1980,"Clarice Starling","Al Pacino");
INSERT INTO ACTORS () VALUES ("Toy Story - Il mondo dei giocattoli",1920,"Dottor Frederick Frankenstein","Clint Eastwood");
INSERT INTO ACTORS () VALUES ("Matrix",1999,"Capitan America","Anthony Edwards");
INSERT INTO ACTORS () VALUES ("Il laureato",1950,"Billy Elliot","Jack Nicholson");
INSERT INTO ACTORS () VALUES ("Il laureato",1950,"Don Camillo","Tom Cruise");
INSERT INTO ACTORS () VALUES ("2001: Odissea nello spazio",1997,"Goose","Gerard Butler");
INSERT INTO ACTORS () VALUES ("Stand by Me - Ricordo di un'estate",1950," Doc  Emmett L. Brown","Michael J. Fox");
INSERT INTO ACTORS () VALUES ("La parola ai giurati",1988,"Colonnello Nathan Jessep","Pat Morita");
INSERT INTO ACTORS () VALUES ("2001: Odissea nello spazio",1997,"Colin Sullivan","Sigourney Weaver");
INSERT INTO ACTORS () VALUES ("Via col vento",1920,"Christopher McCandless","Anthony Hopkins");
INSERT INTO ACTORS () VALUES ("Magnolia",2020,"Lester Burnham","Brad Pitt");
INSERT INTO ACTORS () VALUES ("Carrie - Lo sguardo di Satana",2000,"Tenente Templeton  Sberla  Peck","Peter Fonda");
INSERT INTO ACTORS () VALUES ("Scala al paradiso",1999,"Colin Sullivan","Whoopi Goldberg");
INSERT INTO ACTORS () VALUES ("Shining",1999,"Colin Sullivan","Robin Williams");
INSERT INTO ACTORS () VALUES ("Duello a Berlino",1980,"Il Libano","Peter Fonda");
INSERT INTO ACTORS () VALUES ("Il tesoro della Sierra Madre",1980,"Sarah Connor","John Travolta");
INSERT INTO ACTORS () VALUES ("Alien",1960,"Walt Kowalski","Ewan McGregor");
INSERT INTO ACTORS () VALUES ("C'era una volta il West",1970,"Hunter  Patch  Adams","Jamie Bell");
INSERT INTO ACTORS () VALUES ("Il ritorno dello Jedi",1980,"Morpheus","Colin Clive");
INSERT INTO ACTORS () VALUES ("Trappola di cristallo",1997,"Sergente Bosco Albert  P. E./Pessimo Elemento  Baracus","Dirk Benedict");
INSERT INTO ACTORS () VALUES ("Il padrino",1990,"Tony Montana","Harrison Ford");
INSERT INTO ACTORS () VALUES ("Scala al paradiso",1999,"Frances  Baby ","Harrison Ford");
INSERT INTO ACTORS () VALUES ("Io e Annie",1989,"Glauco Sperandio","Kevin Spacey");
INSERT INTO ACTORS () VALUES ("Tre colori - Film rosso",2020,"Sam Wheat","Ewan McGregor");
INSERT INTO ACTORS () VALUES ("Aliens - Scontro finale",1989,"Il Libano","Bruce Willis");
INSERT INTO ACTORS () VALUES ("Fight Club",2010,"Trinity","Fernandel");
INSERT INTO ACTORS () VALUES ("Batman Begins",2010,"John Keating","George Peppard:");


INSERT INTO AWARDS () VALUES ("Io e Annie",1989,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Duello a Berlino",1980,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Guerre stellari",1960,"Oscar, Best Film",'WON');
INSERT INTO AWARDS () VALUES ("A qualcuno piace caldo",1960,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Taxi Driver",1920,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("Viaggio a Tokyo",2020,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("La grande fuga",1999,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("I 400 colpi",1990,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Guerre stellari",1960,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Guerre stellari",1960,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Fight Club",2010,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("L'Impero colpisce ancora",1988,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il buono, il brutto, il cattivo",1999,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Fronte del porto",2000,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il Signore degli Anelli - La Compagnia dell'Anello",1920,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Apocalypse Now",1999,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il padrino - Parte II",1997,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Cantando sotto la pioggia",2020,"Oscar, Best Director",'NOMINATED');
INSERT INTO AWARDS () VALUES ("La grande fuga",1999,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Arancia meccanica",1999,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il cavaliere oscuro",1970,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Velluto blu",1999,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il ritorno dello Jedi",1980,"Oscar, Best Film",'WON');
INSERT INTO AWARDS () VALUES ("Le iene",2001,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("La dolce vita",1960,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Pulp Fiction",1960,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("C'era una volta in America",1960,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Butch Cassidy",1980,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("La donna che visse due volte",1920,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Ritorno al futuro",2000,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("American Beauty",1980,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Stand by Me - Ricordo di un'estate",1950,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Matrix",1999,"Oscar, Best Film",'WON');
INSERT INTO AWARDS () VALUES ("Il padrino - Parte II",1997,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Va' e vedi",1997,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Re per una notte",1988,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Viale del tramonto",2000,"Oscar, Best Film",'WON');
INSERT INTO AWARDS () VALUES ("Incontri ravvicinati del terzo tipo",2010,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("E.T. l'extra-terrestre",1989,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Heat - La sfida",1960,"Oscar, Best Director",'NOMINATED');
INSERT INTO AWARDS () VALUES ("This Is Spinal Tap",1980,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("L'Impero colpisce ancora",1988,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Toy Story - Il mondo dei giocattoli",1920,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Lo spirito dell'alveare",1980,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("La sottile linea rossa",1988,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Donnie Darko",1920,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Brazil",2001,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("2001: Odissea nello spazio",1997,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Viale del tramonto",2000,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Arancia meccanica",1999,"Oscar, Best Director",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il padrino - Parte II",1997,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Trappola di cristallo",1997,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Taxi Driver",1920,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("I sette samurai",2020,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Incontri ravvicinati del terzo tipo",2010,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Il terzo uomo",1950,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("I soliti sospetti",2020,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Viale del tramonto",2000,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Manhattan",1999,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("Il laureato",1950,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Toy Story - Il mondo dei giocattoli",1920,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Il cavaliere oscuro",1970,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Magnolia",2020,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Matrix",1999,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Manhattan",1999,"Oscar, Best Film",'WON');
INSERT INTO AWARDS () VALUES ("Guerre stellari",1960,"Oscar, Best Director",'NOMINATED');
INSERT INTO AWARDS () VALUES ("2001: Odissea nello spazio",1997,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Terminator 2 - Il giorno del giudizio",2020,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Quei bravi ragazzi",1950,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("La signora del venerdi",1999,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il laureato",1950,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("I sette samurai",2020,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Via col vento",1920,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("8",1988,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il dottor Stranamore",1989,"Oscar, Best Actress",'WON');
INSERT INTO AWARDS () VALUES ("Heat - La sfida",1960,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Heat - La sfida",1960,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("Il mucchio selvaggio",1980,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Il cavaliere oscuro",1970,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("C'era una volta in America",1960,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Andrej Rublev",1990,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Heat - La sfida",1960,"Oscar, Best Actress",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Heat - La sfida",1960,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Harold e Maude",1980,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Pulp Fiction",1960,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("La grande fuga",1999,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Donnie Darko",1920,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Donnie Darko",1920,"Oscar, Best Effects",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Spartacus",1950,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("Le iene",2001,"Oscar, Best Actor",'NOMINATED');
INSERT INTO AWARDS () VALUES ("I sette samurai",2020,"Oscar, Best Actor",'WON');
INSERT INTO AWARDS () VALUES ("Scala al paradiso",1999,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Schindler's List",1970,"Oscar, Best Director",'WON');
INSERT INTO AWARDS () VALUES ("Sangue blu",1980,"Oscar, Best Picture",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Blade Runner",2001,"Oscar, Best Picture",'WON');
INSERT INTO AWARDS () VALUES ("Quei bravi ragazzi",1950,"Oscar, Best Director",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Taxi Driver",1920,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("2001: Odissea nello spazio",1997,"Oscar, Best Film",'NOMINATED');
INSERT INTO AWARDS () VALUES ("Harold e Maude",1980,"Oscar, Best Effects",'WON');
INSERT INTO AWARDS () VALUES ("Il mucchio selvaggio",1980,"Oscar, Best Actor",'NOMINATED');
